### ISSUE TITLE
Spurious ) in package.xml

### ISSUE THREAD

**Issue by klutometis** [ieure/php_repl#1]
A spurious ) in package.xml was causing `pear package' to fail for me. Patch:

<pre>
diff --git a/package.xml b/package.xml
index 7429185..51c9660 100644
--- a/package.xml
+++ b/package.xml
@@ -41,7 +41,7 @@
                     &lt;tasks:replace from="@package_version@" to="version"
                                    type="package-info"/>
 
-                &lt;/file>)
+                &lt;/file>
             &lt;/dir>
             &lt;dir name="scripts">
                 &lt;file name="php-repl" role="script" install-as="php-repl"
</pre>

**Comment by hron** [comment]
+1. You should apply this patch. ;]
