### ISSUE TITLE
enable readline?

### ISSUE THREAD

**Issue by ivanoats** [ieure/php_repl#3]
I must be missing something. How do you enable readline? I have tried the following in .phpreplrc
- readline = "true"
- readline = "yes"
- readline = "1"

but they are all throwing exceptions

`

> php-repl
> PHP Fatal error:  Call to undefined function readline() in /usr/local/Cellar/php/5.3.3/lib/php/PHP/Repl.php on line 171
> PHP Stack trace:
> PHP   1. {main}() /usr/local/Cellar/php/5.3.3/bin/php-repl:0
> PHP   2. PHP_Repl->run() /usr/local/Cellar/php/5.3.3/bin/php-repl:21
> PHP   3. PHP_Repl->read() /usr/local/Cellar/php/5.3.3/lib/php/PHP/Repl.php:132
> `

I do have readline installed (via homebrew on mac os x)

**Comment by ieure** [comment]
While you have libreadline installed, your PHP was not compiled with the readline extension. You need to recompile it; see http://www.php.net/manual/en/readline.installation.php

**Comment by ivanoats** [comment]
ok, thanks for the tip. I recompiled php with readline and it works with readline ="1" in .phpreplrc
